### ISSUE TITLE
Speed up puppet

### ISSUE THREAD

**Issue by penguian** [ACCESS-NRI/accessdev-Trac-archive#187]
|    by saw562@nci.org.au

___

Puppet runs are annoyingly slow, perhaps some of this can be sped up:

```
  time: 
    vcsrepo: 52.220822
    service: 6.782042
    resources: 0.000167
    firewall: 0.008287
    filebucket: 0.000397
    package: 0.738574
    file: 19.4422419999999
    augeas: 1.046394
    ini_setting: 0.085322
    file_line: 0.038554
    yumrepo: 0.357354
    total: 125.003366
    config_retrieval: 16.300388
    mount: 0.01383
    exec: 27.944886
    last_run: 1430366855
    schedule: 0.001174
    postgresql_conf: 0.00034
    notify: 0.000987
    cron: 0.003765
    user: 0.001009
    host: 0.007327
    group: 0.007755
    anchor: 0.00175
```

Particularly checking repositories takes nearly a minute

___
_Issue migrated from [trac:187](https://accessdev.nci.org.au/trac/187) at 2024-01-31 18:12:45 +1100_
